### ISSUE TITLE
Simple example for vanilla JS usage

### ISSUE THREAD

**Issue by josephrocca** [drifting-in-space/y-sweet#187]
It'd be really helpful for me if there were a simple, end-to-end "hello world" type example which is basically:

1. Run this command to start your server (just add s3 + credentials, or whatever)
2. Create this `index.html` with this JS code (just imported from jsdelivr/unpkg for this demo - no npm/build/etc.)
3. Create this simple `index.js` and run `node index.js`

And now you simply open `http://localhost:3000?room=75hdo3uud7ji`, and you can e.g. type in a textarea and other people in the same room can see/edit it too.

This would help me see how it works from a very simple example, and then I can launch of from there and start fiddling with it, 
 reading through the docs, and explore the other demos.

I don't use Next.js or React, so that's probably the main reason I'm having trouble understanding how it all works, but I also think it's kinda hard to see what `y-sweet` "*is*" from the current readme/docs - i.e. what sort of API does it expose, how do I actually use it. A really simple vanilla JS "hello world" would help me get to the "aha!" I think.

**Comment by rolyatmax** [comment]
Hey @josephrocca - I think this is a great idea. We'll try to pull one together for you!

**Comment by rolyatmax** [comment]
Hi @josephrocca! I just added a VanillaJS example in `examples/vanilla`. Let me know if that helps!

**Comment by josephrocca** [comment]
Thanks you so much :pray: So it's basically as easy as creating a yjs doc, and then connecting it to the server:
```js
// Run this server: https://github.com/drifting-in-space/y-sweet/blob/main/examples/vanilla/src/server.js

import * as Y from 'yjs';
import { createYjsProvider } from '@y-sweet/client';

// Get the client token from the y-sweet server. This is basically the user's "password" to edit the "myCoolDoc123" doc.
let clientToken = await fetch("http://localhost:9090/client-token?doc=myCoolDoc123").then(r => r.json());

// Create the yjs doc and link it to the y-sweet server:
const doc = new Y.Doc();
createYjsProvider(doc, clientToken, { disableBc: true });

// Now use the doc like a normal yjs doc!
let sharedMap = doc.getMap('thing');
sharedMap.set("foo", 123);
```
If that's all there is to it, then something very roughly like that would have been a super, super useful thing for me to see in the readme. That would have gotten me to 'aha!' instantly. Can't speak for others though, of course!

Thanks again for this!! Going to give this a try tonight.

**Comment by rolyatmax** [comment]
@josephrocca Yup! That's right. Good point on making that clearer in the docs. Will update those soon! One thing to point out - the line where you fetch the `clientToken` should run server-side and most likely include a token for authenticating with your y-sweet server. We recommend using the `getOrCreateDoc` helper function from `@y-sweet/sdk`:

```js
// CONNECTION_STRING is a value that combines the y-sweet server endpoint with auth credentials
const clientToken = await getOrCreateDoc(docId, CONNECTION_STRING)
```

Curious to know how things worked out for you!

**Comment by josephrocca** [comment]
@rolyatmax For some reason that server.js isn't able to connect to the Y-Sweet server in the little test I did. Here's what I did, step by step:

Setup:
```
mkdir ysweet-test && cd ysweet-test
npm init -y
npm install express cors @y-sweet/sdk
npx y-sweet@latest serve
```
Note the connection string from  that `npx` command and use it in this `index.mjs`:
```js
import fs from 'fs';
import express from 'express';
import cors from 'cors';
import { getOrCreateDoc } from '@y-sweet/sdk';

const app = express();
app.use(cors());

const PORT = 9090; // <-- for *this* server, not the Y-Sweet server

const YSWEET_CONNECTION_STRING = "ys://127.0.0.1:8080";

app.get('/client-token', async (req, res) => {
  const docId = req.query.doc ?? undefined;
  if (docId) {
    console.log('Received client token request for doc', docId);
  } else {
    console.log('Received client token request for new doc');
  }
  const clientToken = await getOrCreateDoc(docId, YSWEET_CONNECTION_STRING);
  res.send(clientToken);
})

app.get('/', async (req, res) => {
  res.send(fs.readFileSync("./index.html", "utf8"));
});

app.listen(PORT, () => {
  console.log(`Y-Sweet VanillaJS demo server listening on port ${PORT}`);
});
```
Create `index.html`:
```html
<script type="module">
  import * as Y from 'https://cdn.jsdelivr.net/npm/yjs@13.6.10/+esm';
  import { createYjsProvider } from 'https://cdn.jsdelivr.net/npm/@y-sweet/client@0.0.9/+esm';

  // Get the client token from the y-sweet server. This is basically the user's "password" to edit the "myCoolDoc123" doc.
  let clientToken = await fetch("http://localhost:9090/client-token?doc=myCoolDoc123").then(r => r.json());

  // Create the yjs doc and link it to the y-sweet server:
  const doc = new Y.Doc();
  createYjsProvider(doc, clientToken, { disableBc: true });

  // Now use the doc like a normal yjs doc!
  let mySharedMap = doc.getMap('thing');

  // Update your UI based on `mySharedMap` changes like this, for example:
  mySharedMap.observe((event) => {
    event.keysChanged.forEach((key) => {
      console.log("change detected in mySharedMap:", key, mySharedMap.get(key));
    });
  });

  mySharedMap.set("foo", 123);

  window.mySharedMap = mySharedMap; // just to play with it in the console
</script>
```
Then run `node index.mjs` and visit `http://localhost:9090` in the browser. And when I do, the `index.mjs` server says:
```
_YSweetError: ServerError: Server responded with 404 Not Found. URL: http://127.0.0.1:8080/doc/myCoolDoc123/auth?z=2ca60....
```

And the Y-Sweet server doesn't how any logs - other than the initial:
```
2023-12-03T19:34:34.352858Z  INFO y_sweet: Listening addr=127.0.0.1:8080`
```
It does have two warnings before that (`No auth key set` and `No store set`) but those don't seem related to this 404 problem.

**Comment by rolyatmax** [comment]
Ah - the issue you are running into is due to the `getOrCreateDoc` function expecting either a `docId` for an existing doc or `undefined`, in which case it creates a new doc. It doesn't currently support passing in your own doc ID and having it create a new doc with it. To be fair, though, I think I'd expect a `getOrCreateDoc` function to do what you're expecting it to do - that is, take a docID to create a new doc with it if an existing doc wasn't found.

Let me look into whether there are any reasons why we couldn't make the function behave that way and get back to you!

**Comment by paulgb** [comment]
Yeah, it's poorly named. I'd like to get rid of it altogether (#148) because I think inlining the code is more readable.

**Comment by rolyatmax** [comment]
@josephrocca Given that we're likely to deprecate `getOrCreateDoc` (or change it's functionality), it might make the most sense to do something like this in your server for now:

```ts
const manager = new DocumentManager(CONNECTION_STRING)
const result = await manager.createDoc('myDoc123')
const clientToken = await manager.getClientToken(result.doc, {})
```

**Comment by josephrocca** [comment]
@rolyatmax Hmm, I'm guessing (based on [this](https://docs.y-sweet.dev/types/_y_sweet_sdk.DocCreationRequest.html)) it should be `await manager.createDoc({doc:'myDoc123'})` (though I tried your code too), but it seems to create a new doc each time, rather than getting the existing one if it exists. The server is generating logs like this which ignore the `'myDoc123'` name:
```
2023-12-05T22:12:47.953108Z  INFO y_sweet::server: Created doc doc_id="-QMqEUqtfXY2fhtKHh2MH"
2023-12-05T22:13:03.057255Z  INFO y_sweet::server: Created doc doc_id="XxhQ0hM-peHEb0l2ubRSh"
```
I'm using the same code as above, but just imported `DocumentManager` and swapped out the `getOrCreateDoc` line for your lines.

(Also, can I suggest renaming `doc` to `docId` across the full API? I.e. `result.docId` and `{docId:'myDoc123'}` rather than `result.doc` and `{doc:'myDoc123'}`. I expect a `doc` to be some sort of actual "doc" object, rather than the ID of a doc.)

**Comment by rolyatmax** [comment]
Ah yes! You're totally right about passing in `{ doc: 'myDoc123' }`. Updated my comment above. Also, I agree with you re: `doc` -> `docId`. Will work that into an upcoming update.

**Comment by josephrocca** [comment]
@rolyatmax My comment might not have been super clear - even with `{doc:'myDoc123'}` it's ignoring the name and making up its own doc IDs. The y-sweet server should log `Created doc doc_id="myDoc123"` rather than something like `Created doc doc_id="ydsYk8Nz8j_e2wUqciAJC"`, right? I created a file with just this code:
```
import { DocumentManager } from '@y-sweet/sdk';
const manager = new DocumentManager("ys://127.0.0.1:8080");
const result = await manager.createDoc({doc:"myDoc123"});
```
And it logged:
```
2023-12-05T22:41:18.062608Z  INFO y_sweet::server: Created doc doc_id="MJ_XzgDAnKU_knxuosC88"
```

Also, FWIW, I'd prefer some sort of simple `getOrCreateDoc`-esque API alongside the lower-level stuff - in the spirit of "simple things should be simple, complex things should be possible". As a point of reference, I love how with MongoDB you can just write: `await db.collection("foo").insertOne({abc:124})` and it auto-creates the collection and adds the doc. People will of course argue over foot-gun stuff that this can cause, but imo this is a good trade-off.

**Comment by rolyatmax** [comment]
@josephrocca yeah, there are a couple things that should be fixed here. One is that the latest published version of the y-sweet server doesn't have that get-or-create functionality that's been added to the y-sweet server's `/new` endpoint. In other words, if you run `manager.createDoc({ doc: 'abc' })` and you're running the y-sweet server with `npx y-sweet@latest serve`, I think it'll create a new doc, ignoring the ID you've passed in. However, if you're running the y-sweet server that's in the y-sweet repo right now (`cargo run serve` from `crates/y-sweet`), that `manager.createDoc({ doc: 'abc' })` call should create a new doc with the ID you've provided.

I'm going to get all this cleaned up tomorrow, including your `doc` -> `docId` suggestion. Here's the SDK functions I have mind (all on the `DocumentManager` class), let me know what you think:

## `createDoc(docDefinition?: { docId: string })`
`docDefinition` is optional. If provided, it tries to create a new doc with the given ID, otherwise it'll generate a random ID. If a doc already exists with the given ID, it'll fail.

## `getClientToken(docId: string)`
`docId` is required. returns a client token with read/write access to the given doc

## `getOrCreateDocAndToken(docDefinition?: { docId: string })`
Essentially runs `createDoc(docDefinition)` above. If a doc with the ID already exists, it ignores the error. Then it runs `getClientToken()` with the doc ID that was passed in, or if none was passed in, with the newly generated docId.

That last function name is a mouthful, but I tend to prefer the names be a bit more explicit. What do you think about those functions?

**Comment by josephrocca** [comment]
Sounds great! Yeah `getOrCreateDocAndToken` is a bit long, but I like the explicitness as you say, and can't really think of anything shorter. Maybe `ensureDocWithToken` -- or `getOrCreateDoc` if a token could be cheaply returned by default (in `createDoc` too), assuming that would be desirable in more cases than not, and with an option to disable. But otherwise `getOrCreateDocAndToken` is great - I definitely prefer that over something that requires 2 lines.

**Comment by rolyatmax** [comment]
> Thanks! I tried it out and got `_YSweetError: ServerError: Server responded with 422 Unprocessable Entity`. using npx y-sweet@latest serve and this code:

The issue there is that `createDoc` now just takes a docId as a string - not an object. e.g.: `await manager.createDoc("myDoc123");`

Thanks for the thoughtful feedback - really appreciate you taking the time to write it out!

re: `getOrCreateDocWithToken` - I considered this name initially but thought it sounded like it was meant to get or create a doc using a token. I also don't like the one I went with, haha. I kinda think if we're going for clarity, just having people write two lines instead of one would be worth it:

```ts
const doc = manager.createDoc('myCoolDoc123')
const token = manager.createToken(doc)
```

re: `createDoc` - I agree, I don't really like this name either. I thought about `getDoc`, but that felt a bit ambiguous - what am I actually _getting_ when I'm just passing an ID and it returns the same ID back to me? Maybe `ensureDoc`? I kinda feel like there's no name that doesn't come with some ambiguity, and I was going back and forth so much, that in the end, I just kept the name and the behavior it already had - and added clearer documentation. (I agree, too, that having a `createDoc` function that throws if the document already exists is a good idea, but that behavior required some deeper plumbing changes that I can't take on right now.)

re: the `CONNECTION_STRING` - I agree it looks a little funny having it as the first arg, but it's because `CONNECTION_STRING` is required while `docId` is not. The TypeScript compiler complains when you put required args after optional args, and I agree with it here. Also, reading this invites a lot of confusion, I think: `createDoc(undefined, CONNECTION_STRING)`.

All that said, if there are some changes you feel strongly about and want to open a PR, I'd be down to talk through them and/or the code changes required! Thanks again for being so patient and offering all the feedback; it's been so helpful!

**Comment by josephrocca** [comment]
Ah, my bad RE docId being a string. Working nicely now! And RE naming stuff - yep, all *very* fair points! I'm guessing there's a good reason why it can't just be `const token = manager.getToken('myCoolDoc123')` but I'll leave it to you, since you're clearly thinking pretty carefully about this and are in a much better position to know what's best.

I'll hopefully get a chance to try this out in a more real-world / less hello-world type situation in the next couple of weeks. Thanks again!
